// ///▙▖▙▖▞▞▙▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
// ▛//▞▞ ⟦⎊⟧ :: ⧗-25.61 // LAW ▞▞
// ▞//▞ Transfer Receipt :: ρ{audit}.φ{contract}.τ{law}.λ{immutable} ⫸
// ▙⌱📜 ≔ [⊢{file-exit}⇨{receipt-create}⟿{track}▷{audit-trail}]
// 〔3OX.Ai.law.transfer〕 :: ∎

/// Transfer Receipt Law
/// When a file leaves 0ut.3ox → 1n.3ox, a receipt MUST be generated
/// This is IMMUTABLE LAW - cannot be bypassed

pub struct TransferReceipt {
    // Identity
    pub receipt_id: String,              // Unique: "TR-{timestamp}-{hash}"
    pub sirius_time: String,             // ⧗-YY.DD
    
    // Origin
    pub from_station: String,            // RVNx.BASE, OBSIDIAN.BASE, etc.
    pub from_path: String,               // Full path where file left
    pub from_agent: Option<String>,      // Which AI generated this
    
    // Destination
    pub to_station: String,              // Where file is going
    pub to_path: String,                 // Exact destination path
    pub to_agent: Option<String>,        // Which AI will receive
    
    // File Details
    pub filename: String,                // What's being transferred
    pub file_hash: String,               // SHA256 for verification
    pub file_size: u64,                  // Bytes
    pub file_type: String,               // Extension or MIME
    
    // Transit Details
    pub timestamp_exit: String,          // When file left 0ut.3ox
    pub timestamp_arrival: Option<String>, // When file entered 1n.3ox
    pub transit_method: TransitMethod,   // How it moved
    pub status: TransitStatus,           // Current state
    
    // Task Handoff (CRITICAL)
    pub task_description: Option<String>, // "What to do with this"
    pub next_action: Option<String>,     // "do this or that next"
    pub priority: Priority,              // HIGH | MEDIUM | LOW
    pub dependencies: Vec<String>,       // What must happen first
    
    // Audit Trail
    pub receipt_path: String,            // Where THIS receipt lives
    pub related_receipts: Vec<String>,   // Chain of custody
    pub notes: Option<String>,           // Human/AI notes
}

pub enum TransitMethod {
    RouterScript,      // Via router.py
    ManualMove,        // Human moved it
    SyncTrigger,       // Automated sync
    DirectCopy,        // Script copied it
}

pub enum TransitStatus {
    Created,           // Receipt generated
    InTransit,         // File moving
    Arrived,           // File in destination
    Verified,          // Hash checked
    TaskAssigned,      // Next action set
    Completed,         // Task done
    Error(String),     // Something failed
}

pub enum Priority {
    HIGH,              // Do immediately
    MEDIUM,            // Do soon
    LOW,               // Do when able
    BLOCKING,          // Stops other work
}

/// RECEIPT FILE FORMAT (stored as .receipt.toml)
/// 
/// [identity]
/// receipt_id = "TR-20251007-abc123"
/// sirius_time = "⧗-25.61"
/// 
/// [origin]
/// from_station = "RVNx.BASE"
/// from_path = "RVNx.BASE/!RVNX.OPS/0ut.3ox/report.md"
/// from_agent = "CMD.BRIDGE"
/// 
/// [destination]
/// to_station = "OBSIDIAN.BASE"
/// to_path = "OBSIDIAN.BASE/!1N.3OX OBSIDIAN/project/report.md"
/// to_agent = "LIGHTHOUSE"
/// 
/// [file]
/// filename = "report.md"
/// file_hash = "abc123def456..."
/// file_size = 4096
/// file_type = "text/markdown"
/// 
/// [transit]
/// timestamp_exit = "2025-10-07T00:15:00"
/// timestamp_arrival = "2025-10-07T00:15:02"
/// transit_method = "RouterScript"
/// status = "Arrived"
/// 
/// [task]
/// description = "Review this report and integrate findings into knowledge base"
/// next_action = "Read report → Create wiki links → Tag related notes"
/// priority = "HIGH"
/// dependencies = []
/// 
/// [audit]
/// receipt_path = "!BASE.OPERATIONS/RECEIPTS/2025-10-07/TR-20251007-abc123.receipt.toml"
/// related_receipts = []
/// notes = "Generated by router.py during automated transit"

/// LAWS (immutable rules):

impl TransferReceipt {
    /// LAW 1: Receipt MUST be created before file moves
    pub fn must_create_before_transit() -> bool {
        true  // Non-negotiable
    }
    
    /// LAW 2: Receipt MUST include task description OR next_action
    pub fn must_have_handoff_instruction(&self) -> bool {
        self.task_description.is_some() || self.next_action.is_some()
    }
    
    /// LAW 3: Receipt MUST verify file hash on arrival
    pub fn must_verify_hash_on_arrival(&self) -> bool {
        true  // Integrity check required
    }
    
    /// LAW 4: Receipts are IMMUTABLE once written
    pub fn is_immutable() -> bool {
        true  // Never modify, only append new status
    }
    
    /// LAW 5: Receipt MUST be accessible from both origin and destination
    pub fn must_be_bidirectional_accessible() -> bool {
        true  // Both sides can see the audit trail
    }
}

/// RECEIPT STORAGE OPTIONS:

/// Option A: Travel with file
/// - receipt.toml stored NEXT TO transferred file
/// - Easy to find, always with content
/// - Example: project/report.md + project/report.md.receipt.toml

/// Option B: Separate receipt filing system
/// - Central: !BASE.OPERATIONS/RECEIPTS/{date}/{receipt_id}.receipt.toml
/// - Organized by date/station/priority
/// - Index file tracks all receipts
/// - Example: RECEIPTS/2025-10-07/TR-20251007-abc123.receipt.toml

/// Option C: Both (RECOMMENDED)
/// - Receipt travels WITH file (always accessible)
/// - Copy stored in central registry (audit trail)
/// - Best of both worlds

/// USAGE EXAMPLE:
///
/// When file exits 0ut.3ox:
/// 1. Generate receipt with task instructions
/// 2. Store receipt next to file
/// 3. Copy receipt to central registry
/// 4. Move file with receipt to destination
/// 5. Receiving agent reads receipt for next actions

/// STATUS: LAW SPECIFICATION ⧗-25.61
/// AUTHORITY: 3OX.Ai Core System
/// IMMUTABLE: These rules cannot be changed, only extended

